export const strings = {
    siteTitle: 'Terragrids',
    splashTitle: 'Create a fair, decentralized\nsolar power grid',
    splashDescription: 'Energy for everyone. Built on the blockchain.',
    whatIsTerragrids1: 'Terragrids is an experimental, non-profit, decentralised autonomous organisation (DAO) whose goal is to empower communities and individuals to take back ownership of what nature gives them for free: energy.',
    mission: 'Our Mission',
    howAreWeDoingThis: 'How are we doing this?',
    whatIsTerragrids2: 'Participants in the Terragrids ecosystem (called citizens) can buy digital crypto tokens (NFTs) that have a 1:1 link with unique solar PV cells in the real world. Participants’ tokens make up virtual solar power systems in the Terragrids greenverse. These virtual systems are linked to real solar PV systems installed on the roofs of real people that live in fuel poverty.',
    whatIsTerragrids3: 'Anyone can become a Terragrids citizen. You just need an Algorand Wallet and a passion for sustainability and decentralisation. Terragrids citizens can own, explore, use and trade their tokens to help govern and expand a virtual electricity grid that power towns and villages in the greenverse; most importantly, they help build and expand a real electricity generation grid, which will reduce fuel poverty, help meet global carbon reduction targets, and ensure a better future for the planet.',
    contributeToWhitePaper: 'View and contribute to the whitepaper',
    poweredBy: 'Powered by',
    carbonNegativeBlockchain: 'carbon negative blockchain',
    decentralized: 'Decentralized',
    decentralizedContent: 'Terragrids is decentralized from inception. The whitepaper is a collaborative document where anyone can comment and propose new ideas. The website and the DApp are entirely open source, so that any developers across the globe can contribute to making Terragrids a better platform. Terragrids citizens can acquire DAO governance rights, and they can participate, discuss and vote in internal decisions, although voting is used only as a last resort. Discussion within the DAO governing body should always aim towards building a consensus.',
    buildOnGithub: 'Build Terragrids on Github',
    roadmap: 'Roadmap',
    electron: 'Electron',
    current: 'Current',
    wire: 'Wire',
    circuit: 'Circuit',
    grid: 'Grid',
    concept: 'Concept',
    whitepaper: 'Whitepaper',
    website1_0: 'Website 1.0',
    openSourceSetUp: 'Open source organisation set up on GitHub (website + dapp)',
    webappDesign: 'Web app + dapp design + POC',
    socialCommunities: 'Communities on Discord, Twitter and Reddit set up',
    team1: 'Team inception',
    startedCollaboration: 'Started collaboration with local organisations tackling fuel poverty',
    webappPrototype: 'Web app + dapp prototype developed and showcased on website',
    legalAdvice: 'Legal advice on structure',
    draftTokenomics: 'First draft of tokenomics for the DAO',
    kickstartFunding: 'Kickstart funding campaign planned',
    mediumFirstPost: 'Medium blog 1st post',
    team2: 'Team growth (software developers, partnership coordinators, blockchain advisor)',
    nonProfitSetup: 'Non-profit company incorporation',
    kickstartLaunched: 'Kickstart funding campaign launched',
    tokenomicsFinal: 'DAO tokenomics finalised',
    tokenPresale: 'NFTs whitelist pre-sale (team + advisors)',
    webAppV1: 'Web app + dapp prototype improved to include map, NFTs (land, solar cells)',
    team3: 'Further team expansion to include solar system project managers, 4+ SW developers, blockchain advisors',
    tokenPublicSale: 'NFTs public sale on the primary market',
    pilotSite: 'Identified first site for the pilot project',
    pilotDesign: 'Designed pilot PV solar system',
    installerSelectionStarted: 'Installer selection process started',
    webAppV2: 'Web app + dapp improved to include vehicles and public buildings',
    pilotDone: 'Pilot PV solar system installed and in operation',
    webAppV3: 'Web app + dapp to include real system output monitoring and reporting, DAO governance tools, internal secondary marketplace for NFTs',
    governanceDefined: 'DAO governance defined',
    idoAllocation: 'ICO / IDO for initial utility tokens allocation',
    newHomesSolarSystems: 'Collaboration with local organisations to identify new homes for solar systems',
    newNFTs: 'New NFTs designed'
}
