export const strings = {
    siteTitle: 'Terragrids',
    splashTitle: 'Create a fair, decentralized\nsolar power grid',
    splashDescription: 'Energy for everyone. Built on the blockchain.',
    whatIsTerragrids1: 'Terragrids is an experimental, non-profit, decentralised autonomous organisation (DAO) whose goal is to empower communities and individuals to take back ownership of what nature gives them for free: energy.',
    mission: 'Mission',
    ourMission: 'Our Mission',
    howAreWeDoingThis: 'How are we doing this?',
    whatIsTerragrids2: 'Terragrids is a web3 crowd-funding platform for community renewable energy projects. It is a game built on top of the Algorand blockchain, which runs a small metaverse, where participants can explore, build and develop a sustainable town entirely powered by solar energy. Players buy and own NFTs to develop the Terragrids world on the virtual map. The revenues from the purchase of each NFT will be administered in the Terragrids treasury Algorand wallet and will directly contribute to the planning and delivery of real community renewable energy projects run in partnership with local NGOs across the globe. NFTs will give players governance rights in the management of the Terragrids metaverse, gradually developing Terragrids into a DAO.',
    whatIsTerragrids3: 'Anyone can become a Terragrids citizen. You just need an Algorand Wallet and a passion for sustainability and decentralisation. Terragrids citizens can own, explore, use and trade their tokens to help govern and expand a virtual electricity grid that power towns and villages in the greenverse; most importantly, they help build and expand a real electricity generation grid, which will reduce fuel poverty, help meet global carbon reduction targets, and ensure a better future for the planet.',
    contributeToWhitePaper: 'View and contribute to the whitepaper',
    linkedIn: 'LinkedIn',
    poweredBy: 'Powered by',
    carbonNegativeBlockchain: 'carbon negative blockchain',
    decentralized: 'Decentralized',
    governance: 'Governance & Partnerships',
    governanceContent1: 'Terragrids is building a new concept for funding renewable energy projects at scale. Rather than relying on single individuals to foot the bill, Terragrids seeks to spread the financial investment across the globe. The Terragrids platform provides an online gamified experience for users (i.e. citizens) to invest as little as $10 to buy Non-Fungible Tokens on the energy-efficient Algorand blockchain and build their sustainable towns and communities in the metaverse. Revenues from the sales are placed in a Terragrids treasury Algo crypto-wallet, that everyone can see. Part of this money is used to sustain the business, while most of the revenue is used to plan and install solar PV, working in partnership with local NGOs helping real people living in fuel poverty.',
    governanceContent2: 'Terragrids is being set up as a Decentralised Autonomous Organisation (DAO). Citizens holding at least one NFT can be part of the DAO governing body, monitoring and contributing to its operations. They can also see in detail how their purchase of NFTs in the metaverse directly financed real assets on the ground, thanks to a direct link with them.',
    decentralizedContent: 'Terragrids is decentralized from inception. The whitepaper is a collaborative document where anyone can comment and propose new ideas. The website and the DApp are entirely open source, so that any developers across the globe can contribute to making Terragrids a better platform. Terragrids citizens can acquire DAO governance rights, and they can participate, discuss and vote in internal decisions, although voting is used only as a last resort. Discussion within the DAO governing body should always aim towards building a consensus.',
    buildOnGithub: 'Build Terragrids on Github',
    roadmap: 'Roadmap',
    team: 'The team',
    electron: 'Electron',
    current: 'Current',
    wire: 'Wire',
    circuit: 'Circuit',
    grid: 'Grid',
    concept: 'Concept',
    whitepaper: 'Whitepaper',
    website1_0: 'Website 1.0',
    openSourceSetUp: 'Open source organisation set up on GitHub (website + dapp)',
    webappDesign: 'Web app + dapp design + POC',
    socialCommunities: 'Communities on Discord, Twitter and Reddit set up',
    team1: 'Team inception',
    startedCollaboration: 'Started collaboration with local organisations tackling fuel poverty',
    webappPrototype: 'Web app + dapp prototype developed and showcased on website',
    legalAdvice: 'Legal advice on structure',
    draftTokenomics: 'First draft of tokenomics for the DAO',
    kickstartFunding: 'Kickstart funding campaign planned',
    mediumFirstPost: 'Medium blog 1st post',
    team2: 'Team growth (software developers, partnership coordinators, blockchain advisor)',
    nonProfitSetup: 'Non-profit company incorporation',
    kickstartLaunched: 'Kickstart funding campaign launched',
    tokenomicsFinal: 'DAO tokenomics finalised',
    tokenPresale: 'NFTs whitelist pre-sale (team + advisors)',
    webAppV1: 'Web app + dapp prototype improved to include map, NFTs (land, solar cells)',
    team3: 'Further team expansion to include solar system project managers, 4+ SW developers, blockchain advisors',
    tokenPublicSale: 'NFTs public sale on the primary market',
    pilotSite: 'Identified first site for the pilot project',
    pilotDesign: 'Designed pilot PV solar system',
    installerSelectionStarted: 'Installer selection process started',
    webAppV2: 'Web app + dapp improved to include vehicles and public buildings',
    pilotDone: 'Pilot PV solar system installed and in operation',
    webAppV3: 'Web app + dapp to include real system output monitoring and reporting, DAO governance tools, internal secondary marketplace for NFTs',
    governanceDefined: 'DAO governance defined',
    idoAllocation: 'ICO / IDO for initial utility tokens allocation',
    newHomesSolarSystems: 'Collaboration with local organisations to identify new homes for solar systems',
    newNFTs: 'New NFTs designed',
    founderTech: 'Founder & Tech Lead',
    founderDesign: 'Founder & Design Lead',
    lorenzoBio: 'Hello! I am Lorenzo, a software engineering professional with 20+ years of experience in a large number of different software technologies, programming languages and device platforms.\nI have managed and led development teams as Tech Lead, Engineering Manager and Technical Programme Manager, focusing on delivery, performance and quality metrics.\nI have worked on projects from startups to large corporations at every level of the software stack, from real-time hardware adaptation to backend, frontend, and mobile application development.\nI am passionate about making things happen, from product ideas to customer adoption, always with a “lean-startup” entrepreneurial mindset.\nI have always had a strong interest in renewable energy, sustainable development and tackling climate change. Combining this with my recent interest in blockchain technologies and decentralised applications, I founded Terragrids to help preserve the world’s climate and take concrete actions for those most affected by fuel poverty.',
    ireneBio: 'Hello! I am Irene, an illustrator, graphics desiger and art director with 15+ years of experience in the industry.\nI am a member of the British Association of Illustrators (AOI) and of the Society of Children’s Book Writers and Illustrators (SCBWI).\nApart from drawing, I love cooking, reading, photography, walking and spending time in nature with my family.\nI am the founder of Editartz (https://editartz.com), an online creative community of illustrators from around the world that regularly share their editorial, children’s and pattern design work.\nFrom October 2020 to December 2021, I led "Planet Posters", an art project in partnership with One Planet Conservation Awareness - 12 months’ focus on the environment: https://www.editartz.com/projects/planet-posters.\nFollowing my passion for nature conservation and sustainability, I founded Terragrids as the Design Lead.'
}
